name: final_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.1
  flutter_bloc: ^8.1.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cupertino_icons: ^1.0.2
  sidebarx: ^0.16.0
  liquid_pull_to_refresh: ^3.0.1
  dio: ^5.3.0
  pinput: ^2.2.31
  mask_text_input_formatter: ^2.5.0
  google_nav_bar: ^5.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
